sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - nvm install 6.3.1
  - nvm use 6.3.1
  - cd frontend && npm install
  - mvn -f backend/pom.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -f backend/pom.xml clean package
  - cd frontend && npm test
  - docker-compose build
