version: '2'
services:
  frontend:
    build: frontend
    depends_on:
      - backend
  backend:
    build: backend
    links:
      - database:pgdb
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
  webserver:
    image: nginx
    links:
      - frontend:frontend
      - backend:backend
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
